
PS C:\Users\BlueFors\Documents\p5control-bluefors> python -Xfrozen_modules=off .\BlueForsGUI.py
v4
PS C:\Users\BlueFors\Documents\p5control-bluefors> python -Xfrozen_modules=off .\BlueForsGUI.py
v4
Traceback (most recent call last):
  File "C:\Users\BlueFors\AppData\Local\Programs\Python\Python311\Lib\site-packages\qtconsole\frontend_widget.py", line 843, in _document_contents_change
    self._auto_call_tip()
  File "C:\Users\BlueFors\AppData\Local\Programs\Python\Python311\Lib\site-packages\qtconsole\frontend_widget.py", line 762, in _auto_call_tip
    self._call_tip()
  File "C:\Users\BlueFors\AppData\Local\Programs\Python\Python311\Lib\site-packages\qtconsole\frontend_widget.py", line 772, in _call_tip
    msg_id = self.kernel_client.inspect(code, cursor_pos)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BlueFors\AppData\Roaming\Python\Python311\site-packages\ipykernel\inprocess\client.py", line 139, in inspect
    self._dispatch_to_kernel(msg)
  File "C:\Users\BlueFors\AppData\Roaming\Python\Python311\site-packages\ipykernel\inprocess\client.py", line 193, in _dispatch_to_kernel
    idents, reply_msg = self.session.recv(stream, copy=False)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BlueFors\AppData\Roaming\Python\Python311\site-packages\jupyter_client\session.py", line 928, in recv
    msg_list = socket.recv_multipart(mode, copy=copy)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BlueFors\AppData\Roaming\Python\Python311\site-packages\ipykernel\inprocess\socket.py", line 31, in recv_multipart
    return self.queue.get_nowait()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BlueFors\AppData\Local\Programs\Python\Python311\Lib\queue.py", line 199, in get_nowait
    return self.get(block=False)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BlueFors\AppData\Local\Programs\Python\Python311\Lib\queue.py", line 168, in get  
    raise Empty
_queue.Empty
GUI.py
v4
PS C:\Users\BlueFors\Documents\p5control-bluefors> python -Xfrozen_modules=off .\BlueForsGUI.py    
v4
PS C:\Users\BlueFors\Documents\p5control-bluefors> python -Xfrozen_modules=off .\BlueForsGUI.py    
v4
PS C:\Users\BlueFors\Documents\p5control-bluefors> python -Xfrozen_modules=off .\BlueForsGUI.py    
v4
PS C:\Users\BlueFors\Documents\p5control-bluefors> python -Xfrozen_modules=off .\BlueForsGUI.py    
v4
PS C:\Users\BlueFors\Documents\p5control-bluefors>


                                                   python -Xfrozen_modules=off .\BlueForsGUI.py
v4
PS C:\Users\BlueFors\Documents\p5control-bluefors> python -Xfrozen_modules=off .\BlueForsGUI.py
v4
PS C:\Users\BlueFors\Documents\p5control-bluefors> python -Xfrozen_modules=off .\BlueForsGUI.py
v4
Traceback (most recent call last):
  File "C:\Users\BlueFors\AppData\Local\Programs\Python\Python311\Lib\site-packages\qtconsole\frontend_widget.py", line 843, in _document_contents_change
    self._auto_call_tip()
  File "C:\Users\BlueFors\AppData\Local\Programs\Python\Python311\Lib\site-packages\qtconsole\frontend_widget.py", line 762, in _auto_call_tip
    self._call_tip()
  File "C:\Users\BlueFors\AppData\Local\Programs\Python\Python311\Lib\site-packages\qtconsole\frontend_widget.py", line 772, in _call_tip
    msg_id = self.kernel_client.inspect(code, cursor_pos)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BlueFors\AppData\Roaming\Python\Python311\site-packages\ipykernel\inprocess\client.py", line 139, in inspect
    self._dispatch_to_kernel(msg)
  File "C:\Users\BlueFors\AppData\Roaming\Python\Python311\site-packages\ipykernel\inprocess\client.py", line 193, in _dispatch_to_kernel
    idents, reply_msg = self.session.recv(stream, copy=False)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BlueFors\AppData\Roaming\Python\Python311\site-packages\jupyter_client\session.py", line 928, in recv
    msg_list = socket.recv_multipart(mode, copy=copy)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BlueFors\AppData\Roaming\Python\Python311\site-packages\ipykernel\inprocess\socket.py", line 31, in recv_multipart
ges\ipykernel\inprocess\socket.py", line 31, in recv_multipart       
           ^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BlueFors\AppData\Local\Programs\Python\Python311\Lib           ^^^^^^^^^^^^^^^^^^^^^^^
    return self.get(block=False)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BlueFors\AppData\Local\Programs\Python\Python311\Lib    return self.get(block=Fals\queue.py", line 168, in get
    raise Empty
_queue.Empty
\queue.py", line 168, in get
    raise Empty
_queue.Empty
PS C:\Users\BlueFors\Documents\p5control-bluefors> python -Xfrozen_modules=off .\BlueForsGUI.py
v4                                                 python -Xfrozen_modules=off .\BlueForsGUI.pyents\p5control-bluefors>
v4
PS C:\Users\BlueFors\Documents\p5control-bluefors> python -Xfrozen_modules=off .\BlueForsGUI.py
v4
PS C:\Users\BlueFors\Documents\p5control-bluefors> python -Xfrozen_modules=off .\BlueForsGUI.py
v4
bg stopped
bg stopped
bg stopped
bg stopped
bg stopped
bg stopped
bg stopped
bg stopped
bg stopped
bg stopped
bg stopped
bg stopped
bg stopped
Exception ignored in atexit callback: <function cleanup at 0x000001F82BF1A700>
Traceback (most recent call last):
  File "C:\Users\BlueFors\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyqtgraph\__init__.py", line 322, in cleanup
  File "C:\Users\BlueFors\Documents\p5control\p5control\gui\guidatagw.py", line 90, in __class__   
    return self.dgw.network_safe_getattr(self._secret_netref, '__class__')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BlueFors\Documents\p5control\p5control\gui\guidatagw.py", line 183, in network_safe_getattr
    self.connect_to_filename(error, old_filename)
  File "C:\Users\BlueFors\Documents\p5control\p5control\gui\guidatagw.py", line 233, in connect_to_filename
    sys.exit()
SystemExit:
QThread: Destroyed while thread is still running
PS C:\Users\BlueFors\Documents\p5control-bluefors> python -Xfrozen_modules=off .\BlueForsGUI.py
v4
PS C:\Users\BlueFors\Documents\p5control-bluefors> python -Xfrozen_modules=off .\BlueForsGUI.py
v4
Traceback (most recent call last):
  File "C:\Users\BlueFors\Documents\p5control\p5control\gui\widgets\datagw_plot.py", line 119, in _on_legend_selected
    self.selectedConfig.emit({})
TypeError: DataGatewayPlot.selectedConfig[BasePlotConfig].emit(): argument 1 has unexpected type 'dict'
PS C:\Users\BlueFors\Documents\p5control-bluefors> python -Xfrozen_modules=off .\BlueForsGUI.py
v4
PS C:\Users\BlueFors\Documents\p5control-bluefors> python -Xfrozen_modules=off .\BlueForsGUI.py
v4
PS C:\Users\BlueFors\Documents\p5control-bluefors> python -Xfrozen_modules=off .\BlueForsGUI.py
v4
PS C:\Users\BlueFors\Documents\p5control-bluefors> 